/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "Secondry-Secondry": "#c82d8c",
        "Texts-Colors-text-light": "#fff",
        "Base-Colors-tag-base-white": "#fff",
        "Texts-Colors-text-dark": "#121212",
        "Base-Colors-input-base-violet": "#f1ecf9",
        "Border-or-seperators-Colors-common-seperator": "#e4e4e4",
        "Base-Colors-button-base-white": "#fff",
        "Gradients-primary-gradient-start": "#7f19a0",
        "Gradients-primary-gradient-end": "#c82d8c",
        "Base-Colors-base-grey": "#f6f6f6",
        "Base-Colors-base-light": "#fff",
        "Border-or-seperators-Colors-button-stroke-grey-2": "#e4e4e4",
        "Border-or-seperators-Colors-button-stroke-grey": "#6c6c6c",
        "Texts-Colors-button-text-grey": "#6c6c6c",
        "Border-or-seperators-Colors-Productcard-stroke-grey": "#e4e4e4",
        "Base-Colors-productcard-base-white": "#fff",
        "Border-or-seperators-Colors-button-stroke-grey-3": "#bfbfbf",
        "Texts-Colors-text-grey": "#6c6c6c",
        "Base-Colors-base-light-violet": "#f4ebff",
        "Border-or-seperators-Colors-common-seperator-dark": "#313131",
        "Base-Colors-base-dark": "#121212",
        "Texts-Colors-text-grey-3": "#c2c2c2",
        "Text-color-White": "#fff",
        "Text-color": "#000",
        gainsboro: {
          100: "#e3e3e3",
        },
        whitesmoke: "#eee",
        brown: "#a72627",
        slategray: "#3b667f",
        pink: "#f6c3cc",
        antiquewhite: "#eddec9",
      },
      spacing: {
        "Spacing-3xl": "40px",
        "Spacing-xs": "6px",
        "Spacing-2xs": "4px",
        "Spacing-3xs": "2px",
        "Spacing-m": "12px",
        "Spacing-l": "16px",
        "Spacing-xm": "14px",
        "Spacing-s": "8px",
        "Spacing-4xl": "48px",
        "Spacing-xl": "24px",
        "Spacing-sm": "10px",
        "Spacing-2xl": "32px",
        "Spacing-5xl": "56px",
      },
      fontFamily: {
        "Typography-Font-Family-Primary": "Montserrat",
        "Typography-Font-Family-Primary-Arabic": "Cairo",
        inter: "Inter",
      },
      borderRadius: {
        "Border-Radius-2xl": "12px",
        "Border-Radius-l": "6px",
        "Border-Radius-4xl": "16px",
        "Border-Radius-m": "4px",
      },
    },
    fontSize: {
      "Typography-Font-Sizes-p": "14px",
      "Typography-Font-Sizes-h3": "28px",
      "Typography-Font-Sizes-h5": "18px",
      "Typography-Font-Sizes-h1": "36px",
      "Typography-Font-Sizes-h2": "32px",
      "Typography-Font-Sizes-h4": "24px",
    },
    lineHeight: {
      "Typography-Line-Height-p": "18px",
      "Typography-Line-Height-h3": "34px",
      "Typography-Line-Height-h5": "18px",
      "Typography-Line-Height-h1": "44px",
      "Typography-Line-Height-h2": "39px",
      "Typography-Line-Height-h4": "29px",
    },
    screens: {},
  },
  corePlugins: {
    preflight: false,
  },
};
